---
packages:
  - apache2
  - php5-mysql
  - php5
  - libapache2-mod-php5
  - php5-mcrypt
  - python-mysqldb
  - php5-gd
  - libssh2-php

wp_db_name: wordpress
wp_db_user: wordpress
wp_db_password: wp_db_password
wp_db_host: "192.168.56.110"

auto_up_disable: false
core_update_level: true
wp_sha256sum: 42ca594afc709cbef8528a6096f5a1efe96dcf3164e7ce321e87d57ae015cc82