- name: Load variables
  hosts: master
  connection: local
  gather_facts: False
  tasks:
    - include_vars: "{{ inventory_dir }}/vars/all.yml"
    - include_vars: "{{ inventory_dir }}/vars/master.yml"

- name: Load database login credentials for the deployment
  hosts: master
  roles:
    - role: firewall
      become: yes
    - role: geerlingguy.mysql
      become: yes
