- name: Wordpress |  Base packages | Update apt cache
  apt: update_cache=yes
  become: yes

- name: Wordpress | Base packages | Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items: "{{ packages }}"