- name: HAPROXY | Add haproxy repository
  apt_repository:
    repo: "{{ ha_repo }}"

- name: HAPROXY | Install HA PROXY
  apt: name=haproxy state=present

- name: HAPROXY | Setup Proxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: "restart haproxy" 