mysql_root_password_update: yes
mysql_databases:
    - name: wordpress
      collation: utf8_general_ci
      encoding: utf8
      replicate: 1

mysql_users:
  - name: wordpress
    host: "%"
    password: wp_db_password
    priv: "*.*:ALL"

mysql_replication_role: 'master'
